### PR TITLE
Updates plugin to Capacitor v3

### PR DESCRIPTION
**Pull request by dragermrb**
This PR adds support for Capacitor V3.

- Usage info has changed and updated on Readme.
- Some unused code has been removed.
- Folder structure have been updated to defaults CapacitorV3 plugin.
- Plugin version updated to 2.0.0

### CODE REVIEW

**Comment by calls9-mattwyld** [comment]
eagerly awaiting this to be merged!

**Comment by adam-enzy** [comment]
@stewones Could you look this over? This would be a game changer if I could use this plugin

**Comment by dragermrb** [comment]
Meantime, I have added `dist` folder to my master branch, so you can install it from github:

```
npm install https://github.com/dragermrb/media --save
```

There is a new method, `saveDocument()`, that is not in readme yet.

**Comment by razorsyntax** [comment]
Is there an ETA for when, or if, this gets merged in?

**Comment by gabides** [comment]
@dragermrb do you have an example of a capacitor 3 project using your fork?

I run into the following error on the chrome inspector on android when doing `savePhoto()`:
```
polyfills.js:2697 Unhandled Promise rejection: RuntimeException occurred ; Zone: <root> ; Task: Promise.then ; Value: Error: RuntimeException occurred
    at Object.cap.fromNative ((index):431)
    at <anonymous>:1:18 Error: RuntimeException occurred
    at Object.cap.fromNative (http://localhost/:431:32)
    at <anonymous>:1:18
```

and when doing `getAlbums()` the app crashed with the following error in Android Studio logcat:
```
2021-09-14 00:18:27.712 24626-24826/? E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException: Invalid column DISTINCT bucket_display_name
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at com.getcapacitor.community.media.MediaPlugin._getAlbums(MediaPlugin.java:176)
        at com.getcapacitor.community.media.MediaPlugin.getAlbums(MediaPlugin.java:57)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    
    
    --------- beginning of crash
2021-09-14 00:18:27.713 24626-24826/? E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.yoobic.app, PID: 24626
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:601)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalArgumentException: Invalid column DISTINCT bucket_display_name
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at com.getcapacitor.community.media.MediaPlugin._getAlbums(MediaPlugin.java:176)
        at com.getcapacitor.community.media.MediaPlugin.getAlbums(MediaPlugin.java:57)
```

**Comment by dragermrb** [comment]
Hi @gabides!

I have fixed an issue with Android Q in the `getAlbums()` method.

Regarding `savePhoto()`, sorry, but I don't have any public repository. Remember You cannot install from the `capacitor-3` branch because it does not include the `dist` folder. Here is a basic example:

```bash
ionic start mediaSampleApp blank --type=angular --capacitor
cd ./mediaSampleApp
 
npm i https://github.com/dragermrb/media/tree/master --save
npm i @capacitor/camera --save
 
ionic cap add android
```

File `src/app/home/home.page.ts`

```typescript
import { Component, NgZone } from '@angular/core';
import { Media } from '@capacitor-community/media';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  albums = [];
  lastPhotoSaved = null;

  constructor(private zone: NgZone) {}

  async takeAndSavePhoto() {
    const image = await Camera.getPhoto({
      source: CameraSource.Camera,
      quality: 90,
      allowEditing: false,
      resultType: CameraResultType.Uri,
    });

    const savePhotoResult = await Media.savePhoto({
      path: image.path,
      album: 'My Album',
    });

    this.lastPhotoSaved = savePhotoResult.filePath;

    console.log('savePhotoResult', savePhotoResult);
  }

  async getAlbums() {
    Media.getAlbums().then((getAlbumsResponse) => {
      console.log('getAlbumsResponse', getAlbumsResponse);

      this.zone.run(() => (this.albums = getAlbumsResponse.albums));
    });
  }
}
```


File `src/app/home/home.page.html`
```html
<ion-header>
  <ion-toolbar color="primary">
    <ion-title>
      Capacitor Media
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content class="ion-padding">
  <ion-button (click)="getAlbums()">Get Albums</ion-button>
  <ion-button (click)="takeAndSavePhoto()">Take photo and add to Gallery</ion-button>

  <div *ngIf="lastPhotoSaved">
    <p>Last Photo Saved</p>
    <span class="ion-wrap">{{ lastPhotoSaved | json }}</span>
  </div>

  <ion-list *ngIf="albums.length > 0">
    <ion-label>Album list</ion-label>
    <ion-item *ngFor="let album of albums">
      <ion-label>{{album.name}}</ion-label>
    </ion-item>
  </ion-list>
</ion-content>
```

Build and run

```bash
npm run build
npx cap sync android
ionic cap run android --livereload --host=0.0.0.0
```

**Comment by razorsyntax** [comment]
I don't know if this is the right place for this question.  But I'm using your branch.  Does this also work for saving a filepath to the gallery on iOS?  I have a screenshot image in the temp folder and am trying to save it to the gallery using your branch.   I get the error: "Could not convert fileURL into Data" on iOS.

```
const filePath = '/private/var/mobile/Containers/Data/Application/6E8214B2-A405-4B33-86A2-7EEEB3BB8BC3/tmp/1631978001212.jpg'; // also doesn't work -> Capacitor.convertFileSrc(photoUrl);
const savePhotoResult = await Media.savePhoto({
      path: filePath,
      album: 'My Album',
    });
```

**Comment by dragermrb** [comment]
Hi @razorsyntax 

I have created the fork to use in my own projects and migrate from Cordova to Capacitor but I have not started working on the implementation for IOS yet.

Currently my fork does the same as the original plugin, maybe in a week or two I can work on the IOS version and correct any problems it finds.

In the meantime, I will comment on some points:

- On IOS you must specify an `albumId`, it doesn't work with the album name. It is something that I intend to change on my fork.
- Make sure you can read the local file before add to gallery, perhaps with `Filesystem.readFile()`, from the `@capacitor/filesystem` plugin. Only do this for this sample, not for a real app.

Tell me if I can help you in any other way.

Greetings

**Comment by askilondz** [comment]
Can't seem to save photo to iOS.  I used a similar implementation for this plugin on Capacitor 2 which works but not working with this Capacitor 3 fork.

```javascript
           const albumsObj = await Media.getAlbums();
           const albumName = 'test';

            if (albumsObj.albums) {

                // console.log('ALBUMS: ', albumsObj.albums);
                albums = albumsObj.albums.filter(x => x.name === albumName);

                if (albums.length < 1) {
                    console.log('Creating Album...');
                    await Media.createAlbum({ name: albumName });
                    albums = (await Media.getAlbums()).albums.filter(x => x.name === albumName);
                } else {
                    console.log('Album Exists.');
                }

                albumFound = albums[0];

            }

            console.log('ALBUM: ', albumFound);

            const album = this.platform.is('ios') ? albumFound.identifier : albumFound.name;
            //album id: 2BE0EEF5-6F89-4629-9CE7-0AB2AD9FF98E/L0/040

            //c.uri = file:\/\/\/var\/mobile\/Containers\/Data\/Application\/3F05BDA1-D56B-46BC-BEBA-3F3A7A108F28\/Library\/Caches\/share-photo.jpg

              Media.savePhoto({ path: c.uri, album })
                                .then(async res => {
                                   console.log("Success"
                                })
                                .catch(console.log);
```

I get the error message `{"errorMessage":"Cannot find album","message":"Cannot find album"}` even though the getAlbums finds the album...that error doesnt happen until I try to save the Photo.

Any help is much appreciated.

**Comment by askilondz** [comment]
Ok so the solution to my problem above, in case anyone else runs into this, is an album object with an `id` and `name` is now required where before it was just a string.

```javascript
     const album = {  id: albumFound.identifier, name: albumFound.name };
     Media.savePhoto({ path: c.uri, album })

**Comment by dragermrb** [comment]
Hi @askilondz

Since it looks like the https://github.com/dragermrb/media/tree/capacitor-3 fork is not going to get mixed up, I have incorporated other changes to the api in the master branch. Unfortunately I have not updated the documentation yet.

On IOS: 
```
    Media.savePhoto({
        path: 'path_to_file',
          album: {
            id: '1234567....', // Album ID. ID or NAME are required (ID has prefrerence)
            name: 'Album name', // Optional. If no ID, create new album with this name (if not exists)
        }
    })
```

On Android: 
```
    Media.savePhoto({
        path: 'path_to_file',
          album: {
            id: '1234567....', // Not used
            name: 'Album name', // Required. Creates new album with this name if not exists
        }
    })
```

**Comment by bfinleyui** [comment]
Any ETA on this being merged?  V3 support is quite important, and don't want to try and manually merge just in case something borks

**Comment by stewones** [comment]
hello everyone, sorry for delay.
just merged, tested ios and it's good, didn't test android yet, please have a try on plugin v3 and lemme know.
Thanks for the PR!

**Pull request merged**
