### PR TITLE
feat(ios): support jpeg files instead of png #80

### PR DESCRIPTION
**Pull request by stephan-fischer**
Code changed to support all image formats
Multiple frames also recognised to support gif animations

### CODE REVIEW

**Review by nkalupahana — CHANGES_REQUESTED** [review]
Thanks for making a PR! Always appreciate people who are willing to contribute code. A few things that need to be changed to merge this in:

* The SDWebImage library is in place to convert image formats that aren't supported on iOS (e.g. WebP), so it can't just be removed.
* Because of the differences in how GIFs work, there is already a separate function for handling GIFs in this plugin -- `saveGif`. As such, this modification is not necessary. (There's no way for me to consolidate GIFs into this function either -- I think it has merit, but it's been like this since before I started maintaining this plugin, and so we should probably maintain backwards compatibility for now.)

The correct way to handle this would likely be to not convert the image to PNG if it is one of iOS's supported formats (e.g. JPEG), and to convert it if it isn't. If you're able to take on that change and remove changes for GIFs from this function, I'm happy to merge this in!

**Comment by stephan-fischer** [comment]
@nkalupahana Ok i have a few questions to complete this task.

First, is it possible to use following code, to save images like png, jpg, and gif:

```swift
            PHPhotoLibrary.shared().performChanges({
                let creationRequest = PHAssetChangeRequest.creationRequestForAssetFromImage(atFileURL: fileURL! as URL)

                if let collection = targetCollection {
                    let addAssetRequest = PHAssetCollectionChangeRequest(for: collection)
                    addAssetRequest?.addAssets([creationRequest?.placeholderForCreatedAsset! as Any] as NSArray)
                }
            }
```
If yes, this code could  used to save the standard image files.
Do you know which file formats all supported by this code or by ios?
Otherwise maybe it makes sense to convert the image format to png.

**Comment by nkalupahana** [comment]
(1) Yes, I believe so.
(2) Supported file formats are [here](https://developer.apple.com/library/archive/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/LoadingImages/LoadingImages.html#//apple_ref/doc/uid/TP40010156-CH17-SW7). If you can figure out a way to get the mime type of the input image (with an iOS API or with SDWebImage), and then compare it to the types that don't need to be converted (and convert otherwise), that's probably the way to go.

**Comment by stephan-fischer** [comment]
i tried PHAssetChangeRequest - and webp works also - an image is shown in the library. - > if shared it to my computer. its a valid webp. i also tried heic and it works! (ios 15.4). -> screenshot attached

Could it be, that PHAsset knows all image types, because heic and webp works? 
Than i prefer to easily use the saveGif functionality for all files instead savePhoto. 

Otherwise is possible to easily check the mime or fie extension, if not gif, png or jpeg
the SDWebImage will be used. But if, than it makes sense to check if the image contains alpha.
If alpha -> PNG, if not -> JPEG

What do you mean @nkalupahana ? 

IMG_4C04534F8D47-1

**Comment by stephan-fischer** [comment]
ChatGPT says:

The PHAsset class in the Apple Photos Framework can manage various image and video formats. Here are the common supported formats:

Image Formats:

JPEG (Joint Photographic Experts Group)
PNG (Portable Network Graphics)
GIF (Graphics Interchange Format)
TIFF (Tagged Image File Format)
HEIF (High Efficiency Image Format)
RAW (Uncompressed RAW image)
Video Formats:

H.264-encoded MOV files
H.264-encoded MP4 files
QuickTime MOV files
MPEG-4 files
The exact support can vary depending on the iOS version and the device. New formats may be added with software updates. It's also important to note that certain specialized formats might not be supported in all contexts. Generally, however, using common formats like JPEG for photos and H.264-encoded MOV or MP4 files for videos should be safe.

As for the HEIF format, it was introduced with iOS 11. This means that devices running iOS 11 and later versions should support HEIF. Keep in mind that support for HEIF may also depend on the specific capabilities of the device's hardware.

**Comment by nkalupahana** [comment]
I just ran the example app on your fork to confirm, and as ChatGPT suggests, WebP is not supported -- the image does not save. Again, what should be done is the image mime type should be compared against those of the supported image types (at the link I provided above). If it's supported, don't convert; else convert.

**Comment by stephan-fischer** [comment]
@nkalupahana  you tried CGImage for webp, but you must use instead

` PHAssetChangeRequest.creationRequestForAssetFromImage` with an webp or heic image.
This function works as expected. Could you please test this function?  it works well, (like the screenshot says) on a iphone 8plus with iOS 15.4.

Means there is no reason to use CGImage and convert this.
If ` PHAssetChangeRequest.creationRequestForAssetFromImage`  creates an error on an image type, than a conversion will be interesting - but yesterday i could save all types on ios >= 15.4 (older not tested).

**Comment by stephan-fischer** [comment]
The same code is using NativeScript Camera to save images to the gallery:

[camera.ios.ts#L58](https://github.com/NativeScript/nativescript-camera/blob/68eb8acb4d2616eacc88323e551401d7fdcebb26/src/camera.ios.ts#L58)

```swift
                    if (this._saveToGallery) {
                        PHPhotoLibrary.sharedPhotoLibrary().performChangesCompletionHandler(
                            () => {
                                PHAssetChangeRequest.creationRequestForAssetFromImage(imageSourceResult.ios);
                            },
                            (success, err) => {
                                if (success) {

```

**Comment by stephan-fischer** [comment]
@nkalupahana 
Another solution is, if you want to use the image in an UIImage following code could used
in saveGif and savePhoto with automatic conversion if needed:
```swift

    let imageUrl = URL(string: data)

    SDWebImageDownloader.shared.downloadImage(with: imageUrl, options: [], progress: nil) { (image, data, error, finished) in
       guard let imageData = data else {
           call.reject("Unable to download image from url")
           return
       }

        PHPhotoLibrary.shared().performChanges({
            let creationRequest = PHAssetCreationRequest.forAsset()
            creationRequest.addResource(with: .photo, data: imageData as Data, options: .none)

            if let collection = targetCollection {
                let addAssetRequest = PHAssetCollectionChangeRequest(for: collection)
                addAssetRequest?.addAssets([creationRequest.placeholderForCreatedAsset! as Any] as NSArray)
            }
        }, completionHandler: {success, error in
            if !success {
                call.reject("Unable to save image to album")
            } else {
                call.resolve()
            }
        })
   }
```

**Comment by stephan-fischer** [comment]
New code with SDWebImageDownloader in Pull Request

**Comment by stephan-fischer** [comment]
@nkalupahana what do you think about the new code?

**Pull request merged**
